from .base import BaseSkeleton


class Halpe2617Skeleton(BaseSkeleton):
    def __init__(self):
        joint_names = [
            "CHip",
            "RHip",
            "RKnee",
            "RAnkle",
            "RBigToe",
            "RSmallToe",
            "RHeel",
            "LHip",
            "LKnee",
            "LAnkle",
            "LBigToe",
            "LSmallToe",
            "LHeel",
            "Spine_Lumba5",
            "Spine_Lumba4",
            "Spine_Lumba3",
            "Spine_Lumba2",
            "Spine_Lumba1",
            "Thoracic12",
            "Thoracic11",
            "Thoracic10",
            "Thoracic9",
            "Thoracic8",
            "Thoracic7",
            "Thoracic6",
            "Thoracic5",
            "Thoracic4",
            "Thoracic3",
            "Thoracic2",
            "Thoracic1",
            "Head",
            "Nose",
            "RShoulder",
            "RElbow",
            "RWrist",
            "LShoulder",
            "LElbow",
            "LWrist",
        ]
        connections = [
            ["CHip", "RHip"],
            ["RHip", "RKnee"],
            ["RKnee", "RAnkle"],
            ["RAnkle", "RBigToe"],
            ["RAnkle", "RSmallToe"],
            ["RAnkle", "RHeel"],
            ["CHip", "LHip"],
            ["LHip", "LKnee"],
            ["LKnee", "LAnkle"],
            ["LAnkle", "LBigToe"],
            ["LAnkle", "LSmallToe"],
            ["LAnkle", "LHeel"],
            ["CHip", "Spine_Lumba5"],
            ["Spine_Lumba5", "Spine_Lumba4"],
            ["Spine_Lumba4", "Spine_Lumba3"],
            ["Spine_Lumba3", "Spine_Lumba2"],
            ["Spine_Lumba2", "Spine_Lumba1"],
            ["Spine_Lumba1", "Thoracic12"],
            ["Thoracic12", "Thoracic11"],
            ["Thoracic11", "Thoracic10"],
            ["Thoracic10", "Thoracic9"],
            ["Thoracic9", "Thoracic8"],
            ["Thoracic8", "Thoracic7"],
            ["Thoracic7", "Thoracic6"],
            ["Thoracic6", "Thoracic5"],
            ["Thoracic5", "Thoracic4"],
            ["Thoracic4", "Thoracic3"],
            ["Thoracic3", "Thoracic2"],
            ["Thoracic2", "Thoracic1"],
            ["Thoracic1", "Nose"],
            ["Nose", "Head"],
            ["Thoracic1", "RShoulder"],
            ["RShoulder", "RElbow"],
            ["RElbow", "RWrist"],
            ["Thoracic1", "LShoulder"],
            ["LShoulder", "LElbow"],
            ["LElbow", "LWrist"],
        ]
        super().__init__(joint_names, connections)
        self.set_feet_joints(
            [
                "RAnkle",
                "RBigToe",
                "RSmallToe",
                "RHeel",
                "LAnkle",
                "LBigToe",
                "LSmallToe",
                "LHeel",
            ],
        )
